version: '3.8'

services:
 web:
  build: ./sf_django
  volumes:
   - ./sf_django/:/usr/src/app/

  ports:
   - 80:8000
  env_file:
   - ./.env.dev
   
 db:
  image: postgres:15.1-alpine
  volumes:
   - postgres_data:/var/lib/postgresql/data/
  environment:
   - POSTGRES_USER=hello_django
   - POSTGRES_PASSWORD=hello_django
   - POSTGRES_DB=hello_django_dev
    
 nginx:
  build: ./nginx
  ports:
   - 1337:80
  depends_on:
   - web
   
volumes:
 postgres_data: 

   
  

